import { CreatePatientDto } from "@/features/patient/types/PatientDto";


export interface ExtendedPatientDto extends CreatePatientDto {
    score: number;
    hospital: string;
}

export const mockPatients: ExtendedPatientDto[] = [
    {
        name: "John Doe",
        email: "john.doe@example.com",
        phone_number: "+1234567890",
        password: "SecurePass123!",
        weight: 75,
        height: 178,
        age: 34,
        score: 85,
        hospital: "St. Mary's Hospital",
    },
    {
        name: "Jane Smith",
        email: "jane.smith@example.com",
        phone_number: "+1987654321",
        password: "Passw0rd!@",
        weight: 60,
        height: 165,
        age: 28,
        score: 92,
        hospital: "Central Clinic",
    },
    {
        name: "Michael Johnson",
        email: "michael.johnson@example.com",
        phone_number: "+1123456789",
        password: "123SecurePass!",
        weight: 90,
        height: 182,
        age: 45,
        score: 70,
        hospital: "City General Hospital",
    },
    {
        name: "Emily Davis",
        email: "emily.davis@example.com",
        phone_number: "+1098765432",
        password: "Password321!",
        weight: 65,
        height: 170,
        age: 30,
        score: 88,
        hospital: "Sunrise Medical Center",
    },
    {
        name: "Robert Brown",
        email: "robert.brown@example.com",
        phone_number: "+1222333444",
        password: "Brownie2023!",
        weight: 82,
        height: 175,
        age: 52,
        score: 60,
        hospital: "Northview Hospital",
    },
    {
        name: "Sophia Taylor",
        email: "sophia.taylor@example.com",
        phone_number: "+1333444555",
        password: "S0phia2023",
        weight: 70,
        height: 168,
        age: 26,
        score: 95,
        hospital: "West End Clinic",
    },
    {
        name: "James Wilson",
        email: "james.wilson@example.com",
        phone_number: "+1444555666",
        password: "James123!",
        weight: 85,
        height: 180,
        age: 39,
        score: 78,
        hospital: "City General Hospital",
    },
    {
        name: "Olivia Martinez",
        email: "olivia.martinez@example.com",
        phone_number: "+1555666777",
        password: "Olivia@2024",
        weight: 58,
        height: 160,
        age: 22,
        score: 65,
        hospital: "Sunrise Medical Center",
    },
    {
        name: "David Lopez",
        email: "david.lopez@example.com",
        phone_number: "+1666777888",
        password: "L0pez2025",
        weight: 95,
        height: 185,
        age: 48,
        score: 82,
        hospital: "Northview Hospital",
    },
    {
        name: "Isabella Anderson",
        email: "isabella.anderson@example.com",
        phone_number: "+1777888999",
        password: "Isabella!123",
        weight: 68,
        height: 172,
        age: 33,
        score: 91,
        hospital: "St. Mary's Hospital",
    },
];
