export const analytes = [
  'cea',
  'hemoglobin',
  'calprotectin_feces',
  'ldl',
  'hct',
  'leukocytes',
  'ast',
  'bilirubin',
  'alkaline_phosphatase',
  'basophils',
  'erythroblasts',
  'erythrocytes',
  'mch',
  'mchc',
  'monocytes',
  'mpv',
  'neutrophils',
  'potassium',
] as const;
